name: Build hugo site

# Controls when the action will run.
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: purcell/setup-emacs@master
        with:
          version: '27.2'
      - name: Generate hugo site
        run: make --no-print-directory -j1 md
      - name: Find and Replace image files
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "/ox-hugo/"
          replace: "/dump-brain-with-emacs/ox-hugo/"
          include: "notes/content/**"
          regex: false
      - name: Hugo Actions
        uses: srt32/hugo-action@v0.0.3
        with:
          args: -s notes

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./notes/public
