name: RunTests

on:
  pull_request:
    types:
      - '*'
  push:
    branches:
      - main
      - master
  schedule:
    # Every week: https://crontab.guru/#0_0_*_*_0
    - cron: '0 0 * * 0'

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        emacs_version:
          - 'snapshot'
          - '27.2'
          - '26.3'
          - '25.3'
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
        if: matrix.os != 'windows-latest'
      - uses: jcs090218/setup-emacs-windows@master
        with:
          version: ${{ matrix.emacs_version }}
        if: matrix.os == 'windows-latest'
      - name: Generate hugo site
        run: make --no-print-directory -j1 md
